# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.6
    hooks:
      - id: golangci-lint
        args: ["--fast"]

  - repo: local
    hooks:
      - id: gosec
        name: gosec
        entry: gosec
        language: system
        types: [go]
        pass_filenames: false
        args: ["-exclude-dir=cdk.out", "./..."]
